#!/bin/bash


/usr/bin/poff modem
wait
/bin/sleep 1
/bin/rm /var/www/TMPFS/GSM/PPP
/bin/sleep 1
/bin/systemctl start gammu-smsd.service
wait
/bin/sleep 1
#/usr/local/bin/sms 0733331236 "WARNING"'!'"\rGPRS link is stopped\rSMS commands avalaible"
#wait
#/bin/sleep 1


<<"COMMENT"
/usr/bin/poff modem &&
/bin/sleep 1 &&
/bin/rm /var/www/TMPFS/GSM/PPP &&
/bin/sleep 1 &&
/bin/systemctl start gammu-smsd.service &&
/bin/sleep 1
COMMENT
